---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gohome
  namespace: flux-system
spec:
  suspend: false
  interval: 1m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: gohome
  targetNamespace: default
  timeout: 2m0s
  wait: true
